export const popSongs = [
  {
      id: 1,
      title: "Blank Space",
      artist: "Taylor Swift",
      lyric: " ",
      videoUrl: " ",
      thumbnailUrl: "/thumbnails/Blank Space.jpg",
  },
  {
      id: 2,
      title: "Bubble Gum",
      artist: "NewJeans",
      lyric: " ",
      videoUrl: " ",
      thumbnailUrl: "/thumbnails/Bubble Gum.jpg",
  },
  {
      id: 3,
      title: "Ditto",
      artist: "NewJeans",
      lyric: " ",
      videoUrl: " ",
      thumbnailUrl: "/thumbnails/Ditto.jpg",
  },
  {
    id: 4,
    title: "Don't Let Me Down",
    artist: "The Chainsmokers",
    lyric: " ",
    videoUrl: " ",
    thumbnailUrl: "/thumbnails/Don't Let Me Down.jpg",
},
{
  id: 5,
  title: "I Don't Think That I Like Her",
  artist: "Charlie Puth",
  lyric: " ",
  videoUrl: " ",
  thumbnailUrl: "/thumbnails/I Don't Think That I Like Her.jpg",
},
{
  id: 6,
  title: "Magnetic (Starlight Remix)",
  artist: "ILLIT",
  lyric: " ",
  videoUrl: " ",
  thumbnailUrl: "/thumbnails/Magnetic (Starlight Remix).jpg",
},
{
  id: 7,
  title: "Seven -Clean Ver. (feat. Latto)",
  artist: "정국",
  lyric: " ",
  videoUrl: " ",
  thumbnailUrl: "/thumbnails/Seven -Clean Ver. (feat. Latto).jpg",
},
{
  id: 8,
  title: "Sugar",
  artist: "Maroon 5",
  lyric: " ",
  videoUrl: " ",
  thumbnailUrl: "/thumbnails/Sugar.jpg",
},

];